#include "output_writer.h"
#include <cstdio>

// ---- constants ----

// Type attribute visibility
enum {
    TYPE_ATTRIBUTE_VISIBILITY_MASK = 0x00000007,
    TYPE_ATTRIBUTE_NOT_PUBLIC = 0x00000000,
    TYPE_ATTRIBUTE_PUBLIC = 0x00000001,
    TYPE_ATTRIBUTE_NESTED_PUBLIC = 0x00000002,
    TYPE_ATTRIBUTE_NESTED_PRIVATE = 0x00000003,
    TYPE_ATTRIBUTE_NESTED_FAMILY = 0x00000004,
    TYPE_ATTRIBUTE_NESTED_ASSEMBLY = 0x00000005,
    TYPE_ATTRIBUTE_NESTED_FAM_AND_ASSEM = 0x00000006,
    TYPE_ATTRIBUTE_NESTED_FAM_OR_ASSEM = 0x00000007,
    TYPE_ATTRIBUTE_INTERFACE = 0x00000020,
    TYPE_ATTRIBUTE_ABSTRACT = 0x00000080,
    TYPE_ATTRIBUTE_SEALED = 0x00000100,
    TYPE_ATTRIBUTE_SERIALIZABLE = 0x00002000,
};

// Field attributes
enum {
    FIELD_ATTRIBUTE_FIELD_ACCESS_MASK = 0x0007,
    FIELD_ATTRIBUTE_PRIVATE = 0x0001,
    FIELD_ATTRIBUTE_FAM_AND_ASSEM = 0x0002,
    FIELD_ATTRIBUTE_ASSEMBLY = 0x0003,
    FIELD_ATTRIBUTE_FAMILY = 0x0004,
    FIELD_ATTRIBUTE_FAM_OR_ASSEM = 0x0005,
    FIELD_ATTRIBUTE_PUBLIC = 0x0006,
    FIELD_ATTRIBUTE_STATIC = 0x0010,
    FIELD_ATTRIBUTE_INIT_ONLY = 0x0020,
    FIELD_ATTRIBUTE_LITERAL = 0x0040,
};

// Method attributes
enum {
    METHOD_ATTRIBUTE_MEMBER_ACCESS_MASK = 0x0007,
    METHOD_ATTRIBUTE_PRIVATE = 0x0001,
    METHOD_ATTRIBUTE_FAM_AND_ASSEM = 0x0002,
    METHOD_ATTRIBUTE_ASSEM = 0x0003,
    METHOD_ATTRIBUTE_FAMILY = 0x0004,
    METHOD_ATTRIBUTE_FAM_OR_ASSEM = 0x0005,
    METHOD_ATTRIBUTE_PUBLIC = 0x0006,
    METHOD_ATTRIBUTE_STATIC = 0x0010,
    METHOD_ATTRIBUTE_FINAL = 0x0020,
    METHOD_ATTRIBUTE_VIRTUAL = 0x0040,
    METHOD_ATTRIBUTE_ABSTRACT = 0x0400,
    METHOD_ATTRIBUTE_VTABLE_LAYOUT_MASK = 0x0100,
    METHOD_ATTRIBUTE_REUSE_SLOT = 0x0000,
    METHOD_ATTRIBUTE_NEW_SLOT = 0x0100,
    METHOD_ATTRIBUTE_PINVOKE_IMPL = 0x2000,
};

// Parameter attributes
enum {
    PARAM_ATTRIBUTE_IN = 0x0001,
    PARAM_ATTRIBUTE_OUT = 0x0002,
};

static void write_method_modifiers(FILE* f, const Il2CppMethodDefinition& md) {
    uint32_t flags = md.flags;
    switch (flags & METHOD_ATTRIBUTE_MEMBER_ACCESS_MASK) {
        case METHOD_ATTRIBUTE_PRIVATE:      fprintf(f, "private "); break;
        case METHOD_ATTRIBUTE_PUBLIC:       fprintf(f, "public "); break;
        case METHOD_ATTRIBUTE_FAMILY:       fprintf(f, "protected "); break;
        case METHOD_ATTRIBUTE_ASSEM:
        case METHOD_ATTRIBUTE_FAM_AND_ASSEM: fprintf(f, "internal "); break;
        case METHOD_ATTRIBUTE_FAM_OR_ASSEM:  fprintf(f, "protected internal "); break;
    }
    if (flags & METHOD_ATTRIBUTE_STATIC) fprintf(f, "static ");
    if (flags & METHOD_ATTRIBUTE_ABSTRACT) {
        fprintf(f, "abstract ");
        if ((flags & METHOD_ATTRIBUTE_VTABLE_LAYOUT_MASK) == METHOD_ATTRIBUTE_REUSE_SLOT)
            fprintf(f, "override ");
    } else if (flags & METHOD_ATTRIBUTE_FINAL) {
        if ((flags & METHOD_ATTRIBUTE_VTABLE_LAYOUT_MASK) == METHOD_ATTRIBUTE_REUSE_SLOT)
            fprintf(f, "sealed override ");
    } else if (flags & METHOD_ATTRIBUTE_VIRTUAL) {
        if ((flags & METHOD_ATTRIBUTE_VTABLE_LAYOUT_MASK) == METHOD_ATTRIBUTE_NEW_SLOT)
            fprintf(f, "virtual ");
        else
            fprintf(f, "override ");
    }
    if (flags & METHOD_ATTRIBUTE_PINVOKE_IMPL) fprintf(f, "extern ");
}

// ---- dump.cs ----

int write_dump_cs(const Metadata& m, const Il2CppBinary& bin, const std::string& out_path, const LogFn& log) {
    FILE* f = std::fopen(out_path.c_str(), "wb");
    if (!f) { log("cannot open " + out_path); return -1; }

    TypeResolver tr(m, bin);

    fprintf(f, "// Generated by Il2CppDumper-android\n// Metadata version: %d\n\n", m.header.version);

    // Images
    for (size_t i = 0; i < m.imageDefs.size(); i++) {
        const auto& img = m.imageDefs[i];
        fprintf(f, "// Image %zu: %s - %d\n",
                i, m.read_string(img.nameIndex).c_str(), img.typeStart);
    }
    fprintf(f, "\n");

    size_t totalTypes = m.typeDefs.size();
    log("writing dump.cs (" + std::to_string(totalTypes) + " types)...");

    // Map each typedef index -> owning image name (for methodPointer lookup)
    std::vector<std::string> typedefImage(totalTypes);
    for (const auto& img : m.imageDefs) {
        int end = img.typeStart + (int)img.typeCount;
        std::string imgName = m.read_string(img.nameIndex);
        for (int t = img.typeStart; t < end && (size_t)t < totalTypes; t++) {
            typedefImage[t] = imgName;
        }
    }

    for (size_t typeIdx = 0; typeIdx < totalTypes; typeIdx++) {
        const auto& td = m.typeDefs[typeIdx];
        const std::string& imgName = typedefImage[typeIdx];

        // extends: parent + interfaces
        std::vector<std::string> extends;
        if (td.parentIndex >= 0 && (size_t)td.parentIndex < bin.types().size()) {
            const auto& p = bin.types()[td.parentIndex];
            std::string parentName = tr.typeName(p, false, false);
            if (!td.isValueType() && !td.isEnum() && parentName != "object")
                extends.push_back(parentName);
        }

        std::string ns = m.read_string(td.namespaceIndex);
        fprintf(f, "\n// Namespace: %s\n", ns.c_str());

        // visibility
        uint32_t vis = td.flags & TYPE_ATTRIBUTE_VISIBILITY_MASK;
        switch (vis) {
            case TYPE_ATTRIBUTE_PUBLIC:
            case TYPE_ATTRIBUTE_NESTED_PUBLIC:      fprintf(f, "public "); break;
            case TYPE_ATTRIBUTE_NOT_PUBLIC:
            case TYPE_ATTRIBUTE_NESTED_FAM_AND_ASSEM:
            case TYPE_ATTRIBUTE_NESTED_ASSEMBLY:    fprintf(f, "internal "); break;
            case TYPE_ATTRIBUTE_NESTED_PRIVATE:     fprintf(f, "private "); break;
            case TYPE_ATTRIBUTE_NESTED_FAMILY:      fprintf(f, "protected "); break;
            case TYPE_ATTRIBUTE_NESTED_FAM_OR_ASSEM:fprintf(f, "protected internal "); break;
        }
        if ((td.flags & TYPE_ATTRIBUTE_ABSTRACT) && (td.flags & TYPE_ATTRIBUTE_SEALED)) {
            fprintf(f, "static ");
        } else if (!(td.flags & TYPE_ATTRIBUTE_INTERFACE) && (td.flags & TYPE_ATTRIBUTE_ABSTRACT)) {
            fprintf(f, "abstract ");
        } else if (!td.isValueType() && !td.isEnum() && (td.flags & TYPE_ATTRIBUTE_SEALED)) {
            fprintf(f, "sealed ");
        }

        if (td.flags & TYPE_ATTRIBUTE_INTERFACE) fprintf(f, "interface ");
        else if (td.isEnum()) fprintf(f, "enum ");
        else if (td.isValueType()) fprintf(f, "struct ");
        else fprintf(f, "class ");

        std::string typeName = tr.typeDefName(td, false, true);
        fprintf(f, "%s", typeName.c_str());
        if (!extends.empty()) {
            fprintf(f, " : ");
            for (size_t k = 0; k < extends.size(); k++) {
                if (k) fprintf(f, ", ");
                fprintf(f, "%s", extends[k].c_str());
            }
        }
        fprintf(f, " // TypeDefIndex: %zu\n{\n", typeIdx);

        // Fields
        if (td.field_count > 0 && td.fieldStart >= 0) {
            fprintf(f, "\n\t// Fields\n");
            for (int i = 0; i < td.field_count; i++) {
                size_t fi = (size_t)td.fieldStart + i;
                if (fi >= m.fieldDefs.size()) break;
                const auto& fd = m.fieldDefs[fi];
                if ((size_t)fd.typeIndex >= bin.types().size()) continue;
                const auto& ft = bin.types()[fd.typeIndex];
                uint32_t attrs = ft.attrs;

                fprintf(f, "\t");
                switch (attrs & FIELD_ATTRIBUTE_FIELD_ACCESS_MASK) {
                    case FIELD_ATTRIBUTE_PRIVATE:  fprintf(f, "private "); break;
                    case FIELD_ATTRIBUTE_PUBLIC:   fprintf(f, "public "); break;
                    case FIELD_ATTRIBUTE_FAMILY:   fprintf(f, "protected "); break;
                    case FIELD_ATTRIBUTE_ASSEMBLY:
                    case FIELD_ATTRIBUTE_FAM_AND_ASSEM: fprintf(f, "internal "); break;
                    case FIELD_ATTRIBUTE_FAM_OR_ASSEM:  fprintf(f, "protected internal "); break;
                }
                if (attrs & FIELD_ATTRIBUTE_LITERAL) fprintf(f, "const ");
                else {
                    if (attrs & FIELD_ATTRIBUTE_STATIC) fprintf(f, "static ");
                    if (attrs & FIELD_ATTRIBUTE_INIT_ONLY) fprintf(f, "readonly ");
                }
                std::string ftName = tr.typeName(ft, false, false);
                std::string fName = m.read_string(fd.nameIndex);
                fprintf(f, "%s %s;\n", ftName.c_str(), fName.c_str());
            }
        }

        // Properties
        if (td.property_count > 0 && td.propertyStart >= 0) {
            fprintf(f, "\n\t// Properties\n");
            for (int i = 0; i < td.property_count; i++) {
                size_t pi = (size_t)td.propertyStart + i;
                if (pi >= m.propertyDefs.size()) break;
                const auto& pd = m.propertyDefs[pi];
                std::string pName = m.read_string(pd.nameIndex);

                if (pd.get >= 0) {
                    size_t mi = (size_t)td.methodStart + pd.get;
                    if (mi < m.methodDefs.size()) {
                        const auto& md = m.methodDefs[mi];
                        fprintf(f, "\t");
                        write_method_modifiers(f, md);
                        if ((size_t)md.returnType < bin.types().size()) {
                            fprintf(f, "%s %s { ",
                                    tr.typeName(bin.types()[md.returnType], false, false).c_str(),
                                    pName.c_str());
                        }
                    }
                } else if (pd.set >= 0) {
                    size_t mi = (size_t)td.methodStart + pd.set;
                    if (mi < m.methodDefs.size()) {
                        const auto& md = m.methodDefs[mi];
                        fprintf(f, "\t");
                        write_method_modifiers(f, md);
                        if (md.parameterStart >= 0 && (size_t)(md.parameterStart) < m.parameterDefs.size()) {
                            const auto& par = m.parameterDefs[md.parameterStart];
                            if ((size_t)par.typeIndex < bin.types().size()) {
                                fprintf(f, "%s %s { ",
                                        tr.typeName(bin.types()[par.typeIndex], false, false).c_str(),
                                        pName.c_str());
                            }
                        }
                    }
                }
                if (pd.get >= 0) fprintf(f, "get; ");
                if (pd.set >= 0) fprintf(f, "set; ");
                fprintf(f, "}\n");
            }
        }

        // Methods
        if (td.method_count > 0 && td.methodStart >= 0) {
            fprintf(f, "\n\t// Methods\n");
            for (int i = 0; i < td.method_count; i++) {
                size_t mi = (size_t)td.methodStart + i;
                if (mi >= m.methodDefs.size()) break;
                const auto& md = m.methodDefs[mi];
                if ((size_t)md.returnType >= bin.types().size()) continue;

                // RVA from per-image method pointer table
                uint64_t methodPtr = bin.methodPointer(imgName, md.token);
                fprintf(f, "\n");
                if (md.flags & METHOD_ATTRIBUTE_ABSTRACT || methodPtr == 0) {
                    fprintf(f, "\t// RVA: -1 Offset: -1");
                } else {
                    fprintf(f, "\t// RVA: 0x%llX", (unsigned long long)(methodPtr - bin.imageBase()));
                }
                if (md.slot != 0xFFFF) fprintf(f, " Slot: %u", md.slot);
                fprintf(f, "\n\t");
                write_method_modifiers(f, md);

                const auto& retType = bin.types()[md.returnType];
                std::string mName = m.read_string(md.nameIndex);
                if (md.genericContainerIndex >= 0) {
                    mName += tr.genericContainerParams(md.genericContainerIndex);
                }
                if (retType.byref) fprintf(f, "ref ");
                std::string retName = tr.typeName(retType, false, false);
                fprintf(f, "%s %s(", retName.c_str(), mName.c_str());

                for (int j = 0; j < md.parameterCount; j++) {
                    if (j) fprintf(f, ", ");
                    size_t pi = (size_t)md.parameterStart + j;
                    if (pi >= m.parameterDefs.size()) break;
                    const auto& par = m.parameterDefs[pi];
                    if ((size_t)par.typeIndex >= bin.types().size()) continue;
                    const auto& pt = bin.types()[par.typeIndex];
                    std::string pName = m.read_string(par.nameIndex);
                    if (pt.byref) {
                        if ((pt.attrs & PARAM_ATTRIBUTE_OUT) && !(pt.attrs & PARAM_ATTRIBUTE_IN)) fprintf(f, "out ");
                        else if (!(pt.attrs & PARAM_ATTRIBUTE_OUT) && (pt.attrs & PARAM_ATTRIBUTE_IN)) fprintf(f, "in ");
                        else fprintf(f, "ref ");
                    }
                    std::string ptName = tr.typeName(pt, false, false);
                    fprintf(f, "%s %s", ptName.c_str(), pName.c_str());
                }
                fprintf(f, ") { }\n");
            }
        }

        fprintf(f, "}\n");
    }

    long pos = ftell(f);
    std::fclose(f);
    char sz[64];
    snprintf(sz, sizeof(sz), "%.1f MB", (double)pos / 1024.0 / 1024.0);
    log(std::string("dump.cs written: ") + out_path + " (" + sz + ")");
    return 0;
}

// ---- stringliteral.json ----

int write_stringliteral_json(const Metadata& m, const std::string& out_path, const LogFn& log) {
    FILE* f = std::fopen(out_path.c_str(), "wb");
    if (!f) { log("cannot open " + out_path); return -1; }
    fprintf(f, "[");
    size_t count = m.stringLiterals.size();
    log("writing stringliteral.json (" + std::to_string(count) + " literals)...");
    for (size_t i = 0; i < count; i++) {
        if (i) fprintf(f, ",\n");
        std::string lit = m.read_string_literal((uint32_t)i);
        // JSON escape
        fprintf(f, "{\"index\":%zu,\"length\":%u,\"value\":\"", i, m.stringLiterals[i].length);
        for (char c : lit) {
            unsigned char u = (unsigned char)c;
            switch (c) {
                case '"':  fprintf(f, "\\\""); break;
                case '\\': fprintf(f, "\\\\"); break;
                case '\n': fprintf(f, "\\n"); break;
                case '\r': fprintf(f, "\\r"); break;
                case '\t': fprintf(f, "\\t"); break;
                default:
                    if (u < 0x20) fprintf(f, "\\u%04x", u);
                    else fputc(u, f);
            }
        }
        fprintf(f, "\"}");
    }
    fprintf(f, "]\n");
    long pos = ftell(f);
    std::fclose(f);
    char sz[64];
    snprintf(sz, sizeof(sz), "%.1f MB", (double)pos / 1024.0 / 1024.0);
    log(std::string("stringliteral.json written: ") + out_path + " (" + sz + ")");
    return 0;
}

// ---- script.json ----

int write_script_json(const Metadata& m, const Il2CppBinary& bin, const std::string& out_path, const LogFn& log) {
    FILE* f = std::fopen(out_path.c_str(), "wb");
    if (!f) { log("cannot open " + out_path); return -1; }

    TypeResolver tr(m, bin);

    log("writing script.json (methods with real addresses)...");

    fprintf(f, "{\n  \"ScriptMethod\": [\n");
    size_t methodCount = m.methodDefs.size();
    int written = 0;
    bool first = true;

    // map imageName -> typeStart..typeEnd
    // iterate per image
    for (size_t imgIdx = 0; imgIdx < m.imageDefs.size(); imgIdx++) {
        const auto& img = m.imageDefs[imgIdx];
        std::string imgName = m.read_string(img.nameIndex);
        int typeEnd = img.typeStart + (int)img.typeCount;
        for (int ti = img.typeStart; ti < typeEnd; ti++) {
            if ((size_t)ti >= m.typeDefs.size()) break;
            const auto& td = m.typeDefs[ti];
            for (int mi = 0; mi < td.method_count; mi++) {
                size_t mIdx = (size_t)td.methodStart + mi;
                if (mIdx >= methodCount) break;
                const auto& md = m.methodDefs[mIdx];
                uint64_t addr = bin.methodPointer(imgName, md.token);
                if (addr == 0) continue;
                uint64_t rva = addr - bin.imageBase();

                std::string name = tr.typeDefName(td, true, false) + "$$" + m.read_string(md.nameIndex);

                if (!first) fprintf(f, ",\n");
                first = false;
                fprintf(f, "    {\"Address\": %llu, \"Name\": \"%s\", \"Signature\": \"\", \"TypeSignature\": \"\"}",
                        (unsigned long long)rva, name.c_str());
                written++;
            }
        }
    }
    fprintf(f, "\n  ],\n");

    // ScriptString
    fprintf(f, "  \"ScriptString\": [\n");
    size_t strCount = m.stringLiterals.size();
    for (size_t i = 0; i < strCount; i++) {
        if (i) fprintf(f, ",\n");
        std::string lit = m.read_string_literal((uint32_t)i);
        fprintf(f, "    {\"Address\": %zu, \"Value\": \"", i);
        for (char c : lit) {
            unsigned char u = (unsigned char)c;
            switch (c) {
                case '"':  fprintf(f, "\\\""); break;
                case '\\': fprintf(f, "\\\\"); break;
                case '\n': fprintf(f, "\\n"); break;
                case '\r': fprintf(f, "\\r"); break;
                case '\t': fprintf(f, "\\t"); break;
                default: if (u < 0x20) fprintf(f, "\\u%04x", u); else fputc(u, f);
            }
        }
        fprintf(f, "\"}");
    }
    fprintf(f, "\n  ],\n");
    fprintf(f, "  \"ScriptMetadata\": [],\n  \"ScriptMetadataMethod\": [],\n  \"Addresses\": []\n}\n");

    long pos = ftell(f);
    std::fclose(f);
    char sz[64];
    snprintf(sz, sizeof(sz), "%.1f MB", (double)pos / 1024.0 / 1024.0);
    log(std::string("script.json written: ") + out_path + " (" + sz + ") methods=" + std::to_string(written));
    return 0;
}

// ---- il2cpp.h (stub for now — full port next commit) ----

int write_il2cpp_h(const std::string& out_path, const LogFn& log) {
    FILE* f = std::fopen(out_path.c_str(), "wb");
    if (!f) { log("cannot open " + out_path); return -1; }
    fprintf(f, "// il2cpp.h placeholder — full struct generation next commit\n");
    std::fclose(f);
    log("il2cpp.h written (placeholder)");
    return 0;
}
